services:
    wros2_humble_ws:
        build:
            context: "docker"
            dockerfile: "Dockerfile"
        container_name: wros2_humble_container
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            - /dev:/dev
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./ros2_ws/humble/src/wros2_tutorials:/ros2_ws/src/wros2_tutorials
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/humble/setup.bash && colcon build --executor sequential && bash"
